# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 05:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('stairs', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10, null=True)),
                ('van_size', models.IntegerField(default=1)),
                ('helping_guys', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=1024)),
                ('paid_status', models.BooleanField(default=False)),
                ('quote', models.FloatField(default=0)),
                ('status', models.CharField(default='Unconfirmed', max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='book.Address')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='book.Address')),
                ('stop1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop1', to='book.Address')),
                ('stop2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop2', to='book.Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=128)),
                ('from_postcode', models.CharField(max_length=128)),
                ('to_postcode', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=20)),
                ('licence_number', models.CharField(max_length=10)),
                ('car_size', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Van'),
        ),
    ]
