# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stop1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop1', to='book.Address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stop2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop2', to='book.Address'),
        ),
    ]
