# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRateForVanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('weekday_customer_loading_price', models.IntegerField(default=0)),
                ('weekday_customer_loading_min_price', models.IntegerField(default=0)),
                ('weekend_customer_loading_price', models.IntegerField(default=0)),
                ('weekend_customer_loading_min_price', models.IntegerField(default=0)),
                ('weekday_one_man_loading_price', models.IntegerField(default=0)),
                ('weekday_one_man_loading_min_price', models.IntegerField(default=0)),
                ('weekend_one_man_loading_price', models.IntegerField(default=0)),
                ('weekend_one_man_loading_min_price', models.IntegerField(default=0)),
                ('weekday_two_man_loading_price', models.IntegerField(default=0)),
                ('weekday_two_man_loading_min_price', models.IntegerField(default=0)),
                ('weekend_two_man_loading_price', models.IntegerField(default=0)),
                ('weekend_two_man_loading_min_price', models.IntegerField(default=0)),
                ('weekday_three_man_loading_price', models.IntegerField(default=0)),
                ('weekday_three_man_loading_min_price', models.IntegerField(default=0)),
                ('weekend_three_man_loading_price', models.IntegerField(default=0)),
                ('weekend_three_man_loading_min_price', models.IntegerField(default=0)),
            ],
        ),
    ]
