# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesRelatedToJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('stopping_fee', models.IntegerField(default=0)),
                ('stopping_fee_na', models.IntegerField(default=0)),
                ('flight_stairs_charge', models.IntegerField(default=0)),
                ('flight_stairs_charge_na', models.IntegerField(default=0)),
                ('dist_charge', models.IntegerField(default=0)),
                ('dist_charge_na_min', models.IntegerField(default=0)),
                ('dist_charge_na_max', models.IntegerField(default=0)),
                ('dist_charge_min_price', models.IntegerField(default=0)),
                ('free_running_dist', models.IntegerField(default=0)),
                ('running_dist_charge', models.IntegerField(default=0)),
                ('running_dist_charge_min_price', models.IntegerField(default=0)),
                ('out_of_hours_charge', models.IntegerField(default=0)),
                ('out_of_hours_charge_na', models.IntegerField(default=0)),
                ('one_item_discount', models.IntegerField(default=0)),
                ('one_item_discount_na', models.IntegerField(default=0)),
                ('student_discount', models.IntegerField(default=0)),
                ('student_discount_na', models.IntegerField(default=0)),
                ('london_c_zone_charge', models.IntegerField(default=0)),
                ('london_c_zone_daily_fee', models.IntegerField(default=0)),
                ('london_c_zone_charge_max_price', models.IntegerField(default=0)),
            ],
        ),
    ]
