# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0002_chargesrelatedtojourney'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableVan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=128, unique=True)),
                ('van_type', models.CharField(max_length=128, unique=True)),
                ('van_reg_number', models.CharField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
